version: "3"
services:
  pytest_cov_github_pages:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: pytest_cov_github_pages-image
    container_name: pytest_cov_github_pages-container
    tty: true
